[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "electrofit"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

# Keep only *pure Python* deps not covered in conda env
dependencies = [
  "app",          
  "typer",        # CLI
  "tqdm",         # progress bars
  "tomli_w",      # writing TOML
  'tomli>=2.0.1; python_version < "3.11"',  # backport for old py
  "openmol",
]

[project.scripts]
electrofit = "electrofit.cli.app:main"
electrofit-plot-charges = "electrofit.cli.plot_charges:main"
electrofit-write-symmetry = "electrofit.cli.write_symmetry:main"
electrofit-create-equiv-groups = "electrofit.cli.create_equiv_groups:main"

[tool.hatch.build.targets.wheel]
packages = ["src/electrofit"]