[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "electrofit"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "app",
  "matplotlib",
  "mdtraj",
  "numpy",
  "openbabel-wheel",
  "openmol",
  "pandas",
  "typer",
  'tomli>=2.0.1; python_version < "3.11"',
  "acpype",
  "tqdm",
  "tomli_w",
]

[project.scripts]
electrofit = "electrofit.cli.app:main"

[tool.hatch.build.targets.wheel]
packages = ["src/electrofit"]