[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "electrofit-fep"
version = "0.1.0"
description = "Electrofit FEP workflows"
requires-python = ">=3.12,<3.13"
dependencies = [
  "electrofit>=0.1.0",
  "typer>=0.12",
  "rich>=13",
]



[project.scripts]
electrofit-fep = "electrofit_fep.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/electrofit_fep"]