[project]
name = "my_ligand"
molecule_name = "LIG"
residue_name = "LIG"
charge = 0
protocol = "bcc"
adjust_symmetry = false
ignore_symmetry = false
calculate_group_average = false
atom_type = "gaff2"

[paths]
mdp_dir = "data/MDP"
base_scratch_dir = "/scratch/${USER}/electrofit"

[hpc]
enabled = true
host = "qcm04"
username = "johannal96"
conda_env = "AmberTools23"
shell_init = "~/.bashrc"
use_screen = true
screen_name_prefix = "ef"

[gmx]
script_relpath = "scripts/gmx.sh"
entrypoint = "python -m electrofit.external.gromacs"

[simulation]
forcefield = "amber14sb.ff"

[simulation.box]
type = "dodecahedron"
edge_nm = 1.2

[simulation.ions]
cation = "NA"
anion = "CL"
concentration = 0.15

[gromacs.runtime]
threads = 16
pin = true
