[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "electrofit-analysis"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "MDAnalysis",
  "alchemlyb",
  "joblib",
  "matplotlib",
  "numpy",
  "pandas",
  "rdkit",
  "scikit-learn",
  "scipy",
  "seaborn",
  "typer"
]

[project.scripts]
electrofit-analysis = "electrofit_analysis.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/electrofit_analysis"]